# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
    apt:
        packages:
            - fuse
            - libfuse-dev
            - curl
r_packages:
    - dplyr
    - xml2
    - purrr
    - data.table
    - stringr
    - pkgdown

r_github_packages:
    - ropensci/DataPackageR

before_install:
    - curl https://rclone.org/install.sh | sudo bash
    - source rclone.conf
    - mkdir $HOME/box
    - "rclone mount box: $HOME/box --daemon"

before_script:
    - sh $TRAVIS_BUILD_DIR/copy-data.sh

script:
    - R -e 'DataPackageR::package_build(".", install = FALSE)'

after_success:
    - rm -rd vignettes/
    - Rscript -e 'pkgdown::build_site(document = FALSE)'
    - make readme
    - sh .travis-push.sh
    - cp ./data/promiseData.rda $HOME/box/jolo_projects/promise/data/$(grep -i DataVersion DESCRIPTION | cut -d : -f2 | tr -d '[:space:]' | sed 's/\(.*\)/promiseData_v\1\.rda/')

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: "docs"
