# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
addons:
    apt:
        packages:
            - fuse
            - libfuse-dev
            - curl
r_packages:
    - dplyr
    - xml2
    - purrr
    - data.table
    - stringr

r_github_packages:
    - ropensci/DataPackageR
    - r-lib/pkgdown

before_install:
    - curl https://rclone.org/install.sh | sudo bash
    - source rclone.conf
    - mkdir $HOME/box
    - "rclone mount box: $HOME/box --daemon"

before_script:
    - $TRAVIS_BUILD_DIR/copy-data.sh

script:
    - R -e 'DataPackageR::package_build(".", install = FALSE)'

after_success:
    - Rscript -e 'pkgdown::build_site()'

deploy:
    provider: pages
    skip_cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: docs
