---
title: "PROMISE"
date: '`r Sys.Date()`'
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

## Project overview

```shell
.
├── DATADIGEST
├── datapackager.yml
├── data-raw
│   ├── documentation.R
│   ├── promise.Rmd
│   ├── promise_xml_ecg-GEN.rds
│   └── xml_to_dataframe-GEN.R
├── DESCRIPTION
├── environment.yaml
├── inst
│   ├── doc
│   │   ├── LP-xml_to_dataframe.html
│   │   ├── LP-xml_to_dataframe.Rmd
│   │   ├── promise.html
│   │   └── promise.Rmd
│   └── extdata
│       └── Logfiles
│           ├── processing.log
│           └── promise.html
├── Makefile
├── man
│   ├── promise.Rd
│   └── set_data_path.Rd
├── NAMESPACE
├── NEWS.md
├── promise.Rproj
├── R
│   ├── promise.R
│   └── set_data_path.R
├── Read-and-delete-me
├── README.md
├── README.Rmd
└── vignettes
    ├── LP-xml_to_dataframe.Rmd
    └── promise.Rmd
```

## Installation

You can install promise from github with:

```{r gh-installation, eval = FALSE}
# install.packages("devtools")
devtools::install_github("dloewenstein/promise")
```

You can install promise from Anaconda.org with:

```shell
conda install -c dloewenstein r-promise
```

## Example

In R

```{r example, eval = FALSE}
library("promise")
data(promise)
```
